name: Java CI with Maven - Test and Package

on: pull_request

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: java-setup
        uses: actions/setup-java@corretto-21
      - name: maven
        run: mvn -B package && mvn test
